package com.dicoding.hklfinale

import android.content.Intent
import android.os.Bundle
import android.view.Menu
import android.view.MenuItem
import androidx.appcompat.app.AppCompatActivity
import androidx.appcompat.widget.Toolbar
import androidx.recyclerview.widget.LinearLayoutManager
import androidx.recyclerview.widget.RecyclerView

class MainActivity : AppCompatActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)

        val toolbar: Toolbar = findViewById(R.id.toolbar)
        setSupportActionBar(toolbar)

        val recyclerView: RecyclerView = findViewById(R.id.recyclerView)
        recyclerView.layoutManager = LinearLayoutManager(this)

        val articleList = listOf(
            Article("Sejarah Demokrasi di Indonesia", "Artikel ini menelusuri perjalanan demokrasi di Indonesia dari masa kemerdekaan pada tahun 1945 hingga perkembangan terkini. Dibeberkan bagaimana reformasi politik, pemilihan umum, dan gerakan demokrasi telah membentuk wajah politik Indonesia saat ini.", R.drawable.article_1, "Artikel ini menelusuri perjalanan demokrasi di Indonesia dari masa kemerdekaan pada tahun 1945 hingga perkembangan terkini, mencermati berbagai dinamika politik yang terjadi sepanjang sejarah bangsa. Sejak Proklamasi Kemerdekaan, Indonesia telah mengalami berbagai perubahan signifikan dalam sistem pemerintahan, mulai dari era demokrasi parlementer, masa pemerintahan Orde Lama, hingga sentralisasi kekuasaan pada masa Orde Baru yang ditandai dengan kontrol ketat terhadap partai politik dan kebebasan berekspresi.\n" +
                    "\n" +
                    "Reformasi politik yang terjadi pada akhir 1990-an menjadi tonggak perubahan penting, membuka jalan bagi lahirnya era demokrasi yang lebih terbuka dan inklusif. Proses transisi ini disertai dengan amandemen konstitusi, pembentukan lembaga-lembaga negara baru, serta pelaksanaan pemilihan umum yang semakin transparan dan demokratis. Pemilu yang berlangsung secara langsung, baik di tingkat pusat maupun daerah, memberikan ruang partisipasi yang lebih luas bagi masyarakat dalam menentukan pemimpin mereka.\n" +
                    "\n" +
                    "Gerakan demokrasi yang melibatkan berbagai elemen masyarakat, termasuk mahasiswa, aktivis, dan organisasi masyarakat sipil, juga memainkan peran kunci dalam mengawal perubahan. Gerakan ini tidak hanya mendorong keterbukaan dan akuntabilitas pemerintah, tetapi juga memperjuangkan hak-hak asasi manusia, kebebasan pers, serta penguatan sistem peradilan yang adil dan independen.\n" +
                    "\n" +
                    "Hingga saat ini, perkembangan demokrasi di Indonesia masih terus berlanjut dengan berbagai tantangan, seperti politik identitas, korupsi, dan isu penegakan hukum. Namun demikian, reformasi yang telah dicapai menandai kemajuan penting dalam upaya menciptakan tatanan politik yang lebih demokratis dan berkeadilan. Artikel ini berupaya untuk mengulas perjalanan panjang tersebut, dengan menyoroti peran reformasi politik, pemilihan umum, dan gerakan demokrasi dalam membentuk wajah politik Indonesia yang semakin matang dan berdaya saing di kancah internasional."),
            Article("Peran Pemuda dalam Politik", "Pemuda memiliki peran krusial dalam membentuk arah politik dan kebijakan di masa depan. Artikel ini membahas kontribusi pemuda dalam gerakan sosial dan politik, serta bagaimana mereka dapat mendorong perubahan melalui partisipasi aktif dalam pemilu dan organisasi politik.", R.drawable.article_2, "Pemuda memiliki peran krusial dalam membentuk arah politik dan kebijakan di masa depan, karena mereka merupakan generasi penerus yang akan mewarisi dan melanjutkan pembangunan bangsa. Dengan semangat, ide-ide segar, serta wawasan yang kritis, pemuda sering kali menjadi penggerak utama perubahan sosial dan politik di masyarakat. Artikel ini membahas kontribusi pemuda dalam gerakan sosial dan politik, serta bagaimana mereka dapat mendorong perubahan melalui partisipasi aktif dalam pemilu, organisasi politik, hingga peran mereka dalam berbagai forum dan inisiatif publik.\n" +
                    "\n" +
                    "Sejarah mencatat bahwa pemuda sering kali berada di garis depan gerakan perubahan besar, seperti yang terjadi pada era pergerakan nasional, ketika para pemuda berjuang untuk memerdekakan Indonesia dari penjajahan. Begitu pula pada masa reformasi tahun 1998, ketika gerakan mahasiswa dan pemuda berhasil menumbangkan rezim Orde Baru dan membuka jalan bagi terwujudnya era demokrasi di Indonesia. Peran pemuda dalam gerakan tersebut menunjukkan kekuatan mereka dalam mempengaruhi arah politik dan kebijakan negara.\n" +
                    "\n" +
                    "Selain berperan dalam aksi massa dan gerakan sosial, pemuda juga dapat memberikan kontribusi melalui jalur formal, seperti terlibat dalam partai politik, organisasi kepemudaan, maupun lembaga-lembaga pemerintahan. Dalam partisipasi politik formal, pemuda dapat menyuarakan aspirasi dan kepentingan mereka dengan lebih efektif, baik melalui kursi legislatif, jabatan eksekutif, maupun sebagai penggiat kebijakan publik. Hal ini penting karena keputusan-keputusan yang diambil di ruang-ruang tersebut akan sangat mempengaruhi masa depan generasi muda dan masyarakat secara keseluruhan.\n" +
                    "\n" +
                    "Partisipasi pemuda dalam pemilihan umum, baik sebagai pemilih maupun sebagai calon legislatif, juga merupakan salah satu bentuk keterlibatan yang tak kalah penting. Dengan memilih calon-calon pemimpin yang memiliki visi dan misi yang sejalan dengan nilai-nilai kepemudaan, pemuda dapat menentukan arah kebijakan yang lebih inklusif, pro-kepentingan generasi muda, dan berfokus pada isu-isu yang relevan, seperti pendidikan, lapangan kerja, lingkungan hidup, dan pengembangan kreativitas. Di sisi lain, dengan mencalonkan diri sebagai wakil rakyat, pemuda dapat membawa perubahan dari dalam sistem politik itu sendiri.\n" +
                    "\n" +
                    "Namun, peran pemuda dalam politik tidak terbatas pada ranah formal saja. Banyak pemuda yang juga terlibat dalam gerakan non-pemerintah, seperti komunitas sosial, organisasi masyarakat sipil, serta gerakan advokasi yang mengangkat isu-isu tertentu, seperti hak asasi manusia, kesetaraan gender, pemberdayaan masyarakat, serta perlindungan lingkungan. Melalui gerakan ini, pemuda dapat berkontribusi secara nyata dalam menciptakan perubahan di masyarakat, bahkan di luar jalur politik konvensional.\n" +
                    "\n" +
                    "Dengan semakin berkembangnya teknologi dan media sosial, pemuda juga memiliki peluang yang lebih besar untuk menyuarakan pendapat dan menggalang dukungan terhadap isu-isu yang mereka anggap penting. Media sosial telah menjadi platform strategis bagi pemuda untuk berjejaring, menyebarkan informasi, dan mengorganisir gerakan-gerakan sosial secara lebih cepat dan luas. Ini membuktikan bahwa kontribusi pemuda tidak lagi terbatas oleh batasan-batasan fisik atau struktural.\n" +
                    "\n" +
                    "Artikel ini menyoroti pentingnya partisipasi aktif pemuda dalam berbagai bentuk, baik formal maupun informal, untuk mendorong perubahan sosial dan politik yang positif. Dengan semangat inovasi, idealisme, dan komitmen yang kuat, pemuda Indonesia dapat menjadi agen perubahan yang mampu membawa bangsa ini menuju masa depan yang lebih baik, adil, dan sejahtera."),
            Article("Sistem Pemilihan Umum di Indonesia", "Memahami berbagai jenis sistem pemilihan umum yang digunakan dalam pemilu di Indonesia sangat penting. Artikel ini menjelaskan sistem proporsional, majoritarian, dan campuran, serta bagaimana sistem-sistem ini mempengaruhi hasil pemilu dan representasi politik di DPR.", R.drawable.article_3, "Memahami berbagai jenis sistem pemilihan umum yang digunakan dalam pemilu di Indonesia sangat penting, karena setiap sistem memiliki dampak yang berbeda terhadap proses pemilihan, alokasi kursi, dan representasi politik di parlemen. Secara garis besar, sistem pemilu yang diterapkan di Indonesia mencakup sistem proporsional, sistem mayoritarian (majoritarian), dan sistem campuran. Artikel ini menjelaskan masing-masing sistem tersebut, serta bagaimana penerapannya mempengaruhi hasil pemilu, perolehan suara partai, dan representasi politik di Dewan Perwakilan Rakyat (DPR).\n" +
                    "\n" +
                    "Sistem proporsional adalah sistem yang umum digunakan dalam pemilu legislatif di Indonesia. Dalam sistem ini, alokasi kursi di parlemen didasarkan pada proporsi perolehan suara partai politik di setiap daerah pemilihan (dapil). Dengan kata lain, semakin besar persentase suara yang diperoleh oleh sebuah partai di sebuah dapil, semakin banyak kursi yang akan didapatkan oleh partai tersebut. Keunggulan dari sistem ini adalah kemampuannya untuk menciptakan representasi politik yang lebih inklusif dan mencerminkan keragaman suara pemilih. Sistem proporsional memungkinkan partai-partai kecil untuk tetap mendapatkan kursi di parlemen, sehingga berbagai kepentingan dan aspirasi masyarakat dapat terwakili dengan lebih baik.\n" +
                    "\n" +
                    "Di Indonesia, sistem proporsional yang digunakan adalah sistem proporsional terbuka, di mana pemilih tidak hanya memilih partai politik, tetapi juga calon anggota legislatif yang diusung oleh partai tersebut. Pemilih dapat memilih calon legislatif yang dianggap paling mampu dan kompeten untuk mewakili mereka di parlemen, tanpa terikat pada nomor urut calon yang ditetapkan oleh partai. Hal ini memberikan kesempatan yang lebih besar bagi kandidat individu untuk terpilih berdasarkan popularitas dan kualitas pribadi mereka, bukan semata-mata karena urutan di daftar partai.\n" +
                    "\n" +
                    "Sementara itu, sistem mayoritarian merupakan sistem pemilu yang lebih berorientasi pada perolehan suara mayoritas. Contoh dari sistem ini adalah sistem first-past-the-post (FPTP), di mana kandidat yang memperoleh suara terbanyak di suatu daerah pemilihan akan memenangkan kursi, tanpa memperhitungkan proporsi suara partai secara keseluruhan. Sistem mayoritarian cenderung menciptakan stabilitas politik yang lebih besar karena mendorong terbentuknya pemerintahan yang lebih kuat dan koheren. Namun, kelemahan dari sistem ini adalah potensi ketidakadilan dalam representasi, di mana suara dari partai-partai kecil atau minoritas sering kali terabaikan.\n" +
                    "\n" +
                    "Indonesia juga pernah menerapkan sistem mayoritarian dalam pemilu kepala daerah, seperti pemilihan gubernur, bupati, dan wali kota, yang berlangsung dalam satu putaran atau dua putaran (run-off). Sistem ini memastikan bahwa kandidat yang terpilih adalah yang memiliki dukungan mayoritas, meskipun sering kali menimbulkan polarisasi di tengah masyarakat.\n" +
                    "\n" +
                    "Sistem campuran, yang menggabungkan elemen dari sistem proporsional dan mayoritarian, juga pernah digunakan di beberapa negara untuk memastikan keseimbangan antara stabilitas pemerintahan dan keadilan representasi. Pada sistem ini, sebagian kursi dialokasikan berdasarkan perolehan suara proporsional, sementara sebagian lainnya ditentukan melalui perolehan mayoritas di masing-masing dapil. Sistem campuran ini memungkinkan adanya representasi yang lebih seimbang antara kandidat individu dan partai politik.\n" +
                    "\n" +
                    "Penggunaan sistem pemilu yang berbeda di Indonesia tidak hanya mempengaruhi hasil akhir dari perolehan suara dan alokasi kursi di DPR, tetapi juga berdampak pada dinamika politik yang lebih luas. Sistem proporsional terbuka, misalnya, cenderung mendorong kompetisi internal di dalam partai, karena setiap calon anggota legislatif harus bersaing tidak hanya dengan calon dari partai lain, tetapi juga dengan sesama kandidat di partai yang sama. Hal ini dapat memicu konflik internal, tetapi juga membuka peluang bagi munculnya kader-kader baru yang kompeten dan didukung oleh masyarakat.\n" +
                    "\n" +
                    "Selain itu, pilihan sistem pemilu juga menentukan strategi yang digunakan oleh partai politik dalam kampanye. Pada sistem proporsional, partai cenderung memfokuskan kampanye pada penggalangan dukungan massa yang luas untuk meningkatkan perolehan suara di tingkat nasional. Sebaliknya, pada sistem mayoritarian, partai akan lebih berfokus pada penguatan basis dukungan di dapil-dapil tertentu agar dapat memenangkan kursi secara langsung.\n" +
                    "\n" +
                    "Artikel ini bertujuan untuk memberikan pemahaman yang lebih komprehensif mengenai berbagai sistem pemilu yang digunakan di Indonesia, serta bagaimana masing-masing sistem ini memiliki kelebihan, kelemahan, dan implikasi yang berbeda terhadap representasi politik di DPR. Dengan memahami dinamika dan dampak dari berbagai sistem pemilu ini, pembaca diharapkan dapat memiliki perspektif yang lebih mendalam tentang pentingnya sistem pemilu yang adil, inklusif, dan mampu mencerminkan aspirasi masyarakat secara luas."),
            Article("Politik Identitas di Era Modern", "Dalam era modern, politik identitas menjadi salah satu faktor penting yang mempengaruhi pemilih. Artikel ini mengeksplorasi bagaimana identitas etnis, agama, dan budaya membentuk preferensi politik, serta dampaknya terhadap hubungan antar kelompok di masyarakat.", R.drawable.article_4, "Dalam era modern, politik identitas telah menjadi salah satu faktor penting yang mempengaruhi perilaku dan preferensi pemilih. Fenomena ini terjadi ketika identitas-identitas seperti etnis, agama, dan budaya digunakan sebagai alat mobilisasi politik oleh para aktor politik untuk mendapatkan dukungan dari kelompok-kelompok tertentu. Artikel ini mengeksplorasi bagaimana identitas-identitas tersebut membentuk preferensi politik masyarakat, serta dampaknya terhadap hubungan antar kelompok, stabilitas sosial, dan tatanan politik di suatu negara.\n" +
                    "\n" +
                    "Politik identitas muncul ketika kelompok-kelompok masyarakat yang memiliki identitas sama, seperti kesamaan etnis atau agama, mengidentifikasi dirinya dengan partai politik atau kandidat tertentu yang dianggap mampu mewakili dan memperjuangkan kepentingan mereka. Di Indonesia, misalnya, identitas agama sering kali menjadi elemen yang menentukan dalam pemilihan umum, baik di tingkat daerah maupun nasional. Kandidat yang memiliki afiliasi agama atau latar belakang etnis yang sama dengan mayoritas penduduk di suatu wilayah sering kali mendapatkan dukungan lebih besar karena dianggap lebih memahami dan mampu menyuarakan aspirasi kelompok tersebut.\n" +
                    "\n" +
                    "Dalam beberapa kasus, politik identitas dapat memperkuat ikatan sosial dan solidaritas dalam kelompok yang sama. Namun, di sisi lain, politik identitas juga berpotensi menimbulkan polarisasi di tengah masyarakat. Ketika kampanye politik lebih banyak menekankan perbedaan-perbedaan identitas, seperti suku, agama, ras, dan antargolongan (SARA), potensi untuk menciptakan ketegangan dan konflik antarkelompok menjadi lebih besar. Hal ini dapat mengakibatkan segregasi sosial, di mana kelompok-kelompok masyarakat lebih cenderung mengutamakan identitas kelompoknya masing-masing dibandingkan dengan identitas nasional yang lebih inklusif.\n" +
                    "\n" +
                    "Selain itu, politik identitas sering kali digunakan sebagai strategi oleh para politisi untuk menarik simpati pemilih. Pada konteks ini, politisi atau partai politik memanfaatkan simbol-simbol keagamaan, adat, atau budaya dalam kampanye mereka untuk memperkuat citra diri sebagai \"pembela\" atau \"representasi\" kelompok tertentu. Misalnya, dengan menampilkan identitas keagamaan yang kuat, seorang kandidat dapat mengirimkan pesan bahwa ia adalah pemimpin yang memiliki komitmen moral dan spiritual yang tinggi, sehingga layak untuk dipilih oleh pemilih yang memiliki latar belakang agama yang sama. Strategi ini, meskipun efektif dalam mengumpulkan dukungan, dapat berisiko memperdalam perpecahan di antara masyarakat.\n" +
                    "\n" +
                    "Dalam konteks pemilu, politik identitas juga dapat mempengaruhi pemetaan politik (political mapping) di suatu wilayah. Wilayah-wilayah dengan mayoritas pemilih yang memiliki identitas etnis atau agama yang sama cenderung memilih kandidat atau partai yang berasal dari latar belakang yang sama. Fenomena ini dapat dilihat dalam pola-pola pemungutan suara di berbagai daerah, di mana partai politik atau kandidat yang diidentifikasi memiliki kesamaan identitas sering kali mendominasi perolehan suara. Akibatnya, politik identitas sering kali menciptakan dominasi kelompok tertentu di wilayah-wilayah tertentu, sementara kelompok minoritas terpinggirkan dalam proses politik.\n" +
                    "\n" +
                    "Lebih jauh lagi, politik identitas juga memiliki dampak yang signifikan terhadap hubungan antar kelompok di masyarakat. Ketika identitas digunakan sebagai alat politik, hubungan antara kelompok yang berbeda sering kali menjadi tegang. Hal ini dapat memicu rasa saling curiga dan permusuhan di antara kelompok-kelompok yang sebelumnya hidup berdampingan secara harmonis. Dampak negatif ini dapat terlihat dalam munculnya narasi \"kami versus mereka\" yang memisahkan kelompok mayoritas dan minoritas. Narasi ini tidak hanya memperlebar jurang perbedaan, tetapi juga mengurangi toleransi, memupuk prasangka, dan pada akhirnya dapat mengarah pada konflik sosial yang lebih serius.\n" +
                    "\n" +
                    "Di sisi lain, politik identitas juga dapat dimanfaatkan untuk tujuan yang lebih positif. Ketika dikelola dengan baik, identitas dapat digunakan sebagai alat untuk memperjuangkan hak-hak kelompok minoritas yang selama ini kurang terwakili atau mengalami diskriminasi. Misalnya, gerakan politik berbasis identitas gender dapat digunakan untuk memperjuangkan kesetaraan gender, sementara gerakan politik berbasis etnisitas dapat berjuang untuk meningkatkan kesejahteraan dan hak-hak komunitas adat yang sering kali terpinggirkan dalam proses pembangunan.\n" +
                    "\n" +
                    "Namun, untuk mencapai hal tersebut, penting bagi para pemimpin politik dan masyarakat luas untuk menyadari bahaya dari penyalahgunaan politik identitas yang hanya bertujuan untuk meraih kekuasaan. Penggunaan identitas yang berlebihan dalam politik dapat menimbulkan fragmentasi sosial yang sulit untuk dipulihkan, terutama jika perbedaan identitas dijadikan alat untuk memanipulasi emosi dan sentimen pemilih. Dalam situasi seperti ini, yang sering kali terjadi adalah munculnya konflik horizontal di antara kelompok-kelompok masyarakat yang berbeda identitas.\n" +
                    "\n" +
                    "Artikel ini menyoroti pentingnya memahami dinamika politik identitas, bukan hanya dari sisi dampaknya terhadap perilaku pemilih, tetapi juga dari perspektif hubungan sosial di masyarakat. Dengan memahami cara politik identitas bekerja, diharapkan masyarakat dapat lebih waspada terhadap politisasi identitas yang dapat mengganggu persatuan bangsa. Selain itu, pemahaman yang lebih mendalam tentang politik identitas dapat membantu para pemangku kepentingan untuk merumuskan strategi politik yang lebih inklusif dan berfokus pada penyelesaian isu-isu kebangsaan yang lebih substantif, daripada terjebak pada narasi identitas yang sempit dan destruktif."),
            Article("Korupsi dan Dampaknya", "Korupsi merupakan isu yang tak kunjung reda dan berdampak negatif terhadap pemerintahan dan masyarakat. Artikel ini membahas berbagai bentuk korupsi, dampaknya terhadap pembangunan dan kepercayaan publik, serta upaya-upaya yang dilakukan untuk pemberantasan korupsi di Indonesia.", R.drawable.article_5, "Korupsi merupakan isu yang tak kunjung reda dan terus menjadi masalah besar di berbagai negara, termasuk Indonesia. Korupsi tidak hanya merugikan keuangan negara, tetapi juga merusak tatanan sosial, ekonomi, dan politik. Artikel ini membahas berbagai bentuk korupsi yang sering terjadi, dampaknya terhadap pembangunan dan kepercayaan publik, serta upaya-upaya yang telah dilakukan untuk pemberantasan korupsi di Indonesia. Dengan pemahaman yang lebih baik tentang kompleksitas masalah ini, diharapkan masyarakat dapat lebih berperan aktif dalam mengawal proses pemberantasan korupsi dan mendukung terciptanya pemerintahan yang bersih dan transparan.\n" +
                    "\n" +
                    "Secara umum, korupsi dapat didefinisikan sebagai penyalahgunaan kekuasaan untuk kepentingan pribadi atau kelompok. Di Indonesia, korupsi sering kali terjadi dalam berbagai bentuk, mulai dari korupsi administratif, seperti suap dan gratifikasi, hingga korupsi sistemik yang melibatkan penggelapan dana publik dan manipulasi proyek-proyek pemerintah. Bentuk korupsi yang paling umum di antaranya adalah suap (bribery), di mana pejabat atau pihak tertentu menerima imbalan untuk mempengaruhi keputusan yang menguntungkan pemberi suap. Selain itu, terdapat pula praktik nepotisme dan kroniisme, di mana posisi atau jabatan penting diberikan kepada keluarga atau kerabat dekat, tanpa memperhatikan kualifikasi dan kompetensi.\n" +
                    "\n" +
                    "Korupsi juga dapat terjadi dalam bentuk penggelembungan anggaran (mark-up) pada proyek-proyek pemerintah, pengalihan dana atau aset negara untuk kepentingan pribadi, serta pemerasan oleh pejabat yang menyalahgunakan wewenangnya untuk meminta uang atau barang dari pihak-pihak tertentu. Semua bentuk korupsi ini tidak hanya menghambat proses pembangunan, tetapi juga menimbulkan kerugian besar bagi masyarakat, baik secara langsung maupun tidak langsung.\n" +
                    "\n" +
                    "Dampak dari korupsi terhadap pembangunan sangat signifikan. Korupsi mengakibatkan alokasi anggaran yang tidak efisien, di mana dana yang seharusnya digunakan untuk membangun infrastruktur, meningkatkan kualitas pendidikan, dan layanan kesehatan justru bocor ke kantong-kantong pribadi oknum koruptor. Akibatnya, kualitas proyek-proyek yang dibiayai oleh negara menjadi rendah, dan masyarakat tidak mendapatkan manfaat yang optimal dari investasi publik tersebut. Misalnya, pembangunan jalan, jembatan, atau fasilitas umum lainnya sering kali tidak sesuai dengan standar, karena sebagian besar anggaran digunakan untuk memperkaya diri pejabat atau pengusaha yang terlibat dalam proyek tersebut. Hal ini menyebabkan kualitas infrastruktur yang buruk, yang pada akhirnya menghambat pertumbuhan ekonomi dan memperburuk kesejahteraan masyarakat.\n" +
                    "\n" +
                    "Selain itu, korupsi juga merusak tatanan sosial dengan menciptakan ketidakadilan dan ketidakpercayaan terhadap institusi pemerintahan. Ketika korupsi menjadi budaya, masyarakat akan merasa bahwa hukum tidak ditegakkan secara adil, dan kepercayaan publik terhadap pemerintah dan lembaga negara akan menurun. Masyarakat yang tidak lagi percaya pada pemerintah cenderung apatis terhadap berbagai program dan kebijakan pemerintah, sehingga partisipasi masyarakat dalam pembangunan pun semakin rendah. Ketidakpercayaan ini dapat memicu ketidakstabilan sosial dan politik, yang pada akhirnya mengganggu proses demokratisasi dan keberlanjutan pembangunan.\n" +
                    "\n" +
                    "Untuk mengatasi permasalahan korupsi yang kompleks ini, pemerintah Indonesia telah melakukan berbagai upaya pemberantasan korupsi, baik melalui pembentukan lembaga antikorupsi, reformasi hukum, hingga kampanye kesadaran publik. Salah satu lembaga yang paling dikenal dalam upaya pemberantasan korupsi di Indonesia adalah Komisi Pemberantasan Korupsi (KPK). Didirikan pada tahun 2002, KPK memiliki kewenangan khusus untuk menyelidiki, menyidik, dan menuntut kasus-kasus korupsi yang melibatkan pejabat negara dan instansi pemerintahan. KPK juga berperan dalam melakukan pencegahan korupsi dengan menyusun regulasi, memberikan rekomendasi kebijakan, serta melakukan sosialisasi antikorupsi di berbagai sektor.\n" +
                    "\n" +
                    "Meskipun demikian, upaya pemberantasan korupsi di Indonesia masih menghadapi banyak tantangan. Salah satunya adalah resistensi dari para pelaku korupsi yang memiliki kekuasaan dan pengaruh yang besar. Dalam beberapa kasus, KPK bahkan mengalami intervensi dan pelemahan melalui revisi undang-undang yang membatasi kewenangannya. Selain itu, lemahnya penegakan hukum terhadap kasus-kasus korupsi juga menjadi hambatan utama, di mana banyak kasus besar yang melibatkan tokoh-tokoh penting berakhir dengan hukuman yang ringan atau bahkan tidak diusut tuntas.\n" +
                    "\n" +
                    "Upaya pemberantasan korupsi juga membutuhkan dukungan dari seluruh elemen masyarakat, baik dari sektor swasta, organisasi masyarakat sipil, maupun masyarakat umum. Pendidikan antikorupsi perlu ditanamkan sejak dini untuk membangun kesadaran tentang pentingnya integritas dan kejujuran. Selain itu, pelaporan oleh masyarakat terhadap kasus-kasus korupsi melalui whistleblowing system dan program perlindungan saksi juga harus diperkuat agar lebih banyak kasus yang bisa terungkap dan diproses secara hukum.\n" +
                    "\n" +
                    "Di tingkat internasional, kerja sama dengan lembaga-lembaga antikorupsi dari negara lain juga penting untuk membatasi ruang gerak para koruptor yang mencoba melarikan diri ke luar negeri. Kerja sama ini dapat dilakukan melalui perjanjian ekstradisi, pertukaran informasi, serta pengembalian aset hasil korupsi yang disembunyikan di luar negeri. Dengan adanya sinergi antara lembaga penegak hukum nasional dan internasional, upaya pemberantasan korupsi dapat berjalan lebih efektif dan memberikan efek jera yang lebih besar.\n" +
                    "\n" +
                    "Secara keseluruhan, pemberantasan korupsi bukanlah tugas yang mudah dan memerlukan komitmen yang kuat dari semua pihak. Diperlukan keberanian, ketegasan, dan konsistensi dalam penegakan hukum untuk memberantas korupsi yang telah mengakar di berbagai lapisan masyarakat. Dengan kolaborasi yang baik antara pemerintah, lembaga antikorupsi, masyarakat sipil, serta dukungan internasional, Indonesia diharapkan dapat membangun tatanan pemerintahan yang bersih, transparan, dan berintegritas. Artikel ini bertujuan untuk memberikan pemahaman yang lebih mendalam mengenai tantangan dan upaya dalam pemberantasan korupsi, serta pentingnya peran aktif seluruh elemen masyarakat untuk mendukung terciptanya Indonesia yang bebas dari korupsi."),
            Article("Diplomasi dan Hubungan Internasional", "Diplomasi memainkan peran penting dalam menjalin hubungan antar negara dan menjaga perdamaian. Artikel ini menjelaskan konsep dasar diplomasi, bagaimana kebijakan luar negeri suatu negara dibentuk, serta tantangan yang dihadapi dalam hubungan internasional saat ini.", R.drawable.article_6, "Diplomasi memainkan peran penting dalam menjalin hubungan antar negara dan menjaga perdamaian dunia. Sebagai salah satu elemen utama dalam kebijakan luar negeri, diplomasi tidak hanya bertujuan untuk mencapai kepentingan nasional suatu negara, tetapi juga menciptakan stabilitas regional dan global. Artikel ini menjelaskan konsep dasar diplomasi, bagaimana kebijakan luar negeri suatu negara dibentuk, serta tantangan yang dihadapi dalam hubungan internasional saat ini. Dengan pemahaman yang lebih baik tentang diplomasi, diharapkan pembaca dapat mengapresiasi peran penting diplomasi dalam menciptakan tata dunia yang harmonis dan sejahtera.\n" +
                    "\n" +
                    "Diplomasi dapat didefinisikan sebagai seni dan praktik negosiasi antar negara untuk mencapai tujuan tertentu tanpa menggunakan kekerasan. Diplomasi mencakup berbagai bentuk interaksi, termasuk pertemuan diplomatik, negosiasi, perjanjian internasional, dan komunikasi resmi antara pemerintah. Sejak zaman dahulu, diplomasi telah menjadi sarana utama untuk menyelesaikan perselisihan antar negara, menghindari konflik bersenjata, dan membangun hubungan yang saling menguntungkan. Diplomasi modern juga mencakup kerja sama dalam bidang ekonomi, keamanan, budaya, dan lingkungan, yang semuanya berperan dalam menciptakan tatanan dunia yang lebih stabil dan damai.\n" +
                    "\n" +
                    "Dalam proses pembentukan kebijakan luar negeri, diplomasi berfungsi sebagai alat untuk mencapai tujuan strategis negara dalam arena internasional. Kebijakan luar negeri sebuah negara dibentuk melalui interaksi antara berbagai aktor domestik dan internasional, termasuk pemerintah, parlemen, masyarakat sipil, sektor swasta, serta organisasi internasional. Pemerintah, yang biasanya diwakili oleh Kementerian Luar Negeri atau Departemen Luar Negeri, memainkan peran sentral dalam merumuskan dan menjalankan kebijakan luar negeri. Proses ini melibatkan analisis mendalam terhadap perkembangan global, identifikasi peluang dan ancaman, serta penetapan prioritas nasional yang akan diperjuangkan di tingkat internasional.\n" +
                    "\n" +
                    "Salah satu prinsip dasar diplomasi adalah keseimbangan kekuasaan (balance of power), di mana negara-negara berusaha menjaga keseimbangan kekuatan untuk mencegah dominasi satu negara atas negara lain. Prinsip ini penting untuk mencegah terjadinya konflik besar, seperti yang pernah terjadi dalam Perang Dunia I dan II. Di samping itu, diplomasi juga didasarkan pada prinsip saling menghormati kedaulatan, integritas wilayah, dan non-intervensi dalam urusan dalam negeri negara lain. Melalui perundingan dan dialog, negara-negara berusaha mencapai kesepakatan yang menghormati kepentingan semua pihak, sehingga perdamaian dan kerja sama internasional dapat terwujud.\n" +
                    "\n" +
                    "Namun, dalam praktiknya, diplomasi sering kali dihadapkan pada berbagai tantangan yang rumit. Salah satu tantangan utama adalah perbedaan kepentingan dan pandangan antara negara-negara yang terlibat. Misalnya, dalam isu perdagangan internasional, negara-negara berkembang mungkin ingin menegosiasikan akses pasar yang lebih besar untuk produk mereka, sementara negara-negara maju lebih fokus pada perlindungan hak cipta dan standar kualitas produk. Dalam situasi ini, negosiator harus menemukan titik temu yang dapat mengakomodasi kepentingan semua pihak agar tercapai kesepakatan yang adil dan berkelanjutan.\n" +
                    "\n" +
                    "Selain itu, perkembangan teknologi informasi dan komunikasi yang pesat juga membawa tantangan baru bagi diplomasi. Kini, informasi dapat menyebar dengan sangat cepat dan tidak terkontrol, yang kadang-kadang dapat memicu ketegangan diplomatik jika ada kesalahpahaman atau penyebaran berita palsu (hoaks). Diplomat dan pejabat pemerintah harus lebih berhati-hati dalam menyampaikan pernyataan dan mengambil tindakan, karena respon dari masyarakat dan aktor internasional dapat muncul dengan sangat cepat dan berpengaruh besar terhadap hubungan antar negara.\n" +
                    "\n" +
                    "Isu-isu global seperti perubahan iklim, terorisme, dan migrasi juga menambah kompleksitas dalam hubungan internasional. Dalam isu perubahan iklim, misalnya, negara-negara harus bernegosiasi mengenai pengurangan emisi karbon dan pembiayaan untuk mitigasi perubahan iklim, yang sering kali melibatkan perbedaan pandangan antara negara-negara berkembang dan negara-negara maju. Negara-negara berkembang cenderung berargumen bahwa mereka membutuhkan dukungan finansial untuk transisi ke energi hijau, sementara negara-negara maju menuntut komitmen yang lebih kuat dari seluruh dunia untuk mengurangi emisi. Kesepakatan internasional seperti Perjanjian Paris adalah hasil dari proses diplomasi yang panjang dan rumit, yang menunjukkan betapa pentingnya kerja sama antar negara dalam mengatasi masalah global.\n" +
                    "\n" +
                    "Di bidang keamanan internasional, diplomasi berperan dalam mencegah konflik dan menyelesaikan sengketa. Perserikatan Bangsa-Bangsa (PBB) adalah salah satu organisasi internasional yang berperan penting dalam diplomasi perdamaian, di mana Dewan Keamanan PBB sering kali menjadi forum utama untuk membahas dan menyelesaikan isu-isu keamanan global. Meski begitu, tantangan seperti perbedaan hak veto di antara anggota tetap Dewan Keamanan sering kali menghambat tercapainya konsensus dalam penanganan konflik-konflik besar, seperti yang terjadi di Suriah, Ukraina, atau Yaman.\n" +
                    "\n" +
                    "Hubungan internasional juga dipengaruhi oleh munculnya kekuatan-kekuatan baru di dunia, seperti Tiongkok dan India, yang semakin meningkatkan perannya di kancah global. Pergeseran kekuatan ini menimbulkan dinamika baru dalam diplomasi internasional, di mana negara-negara harus menyesuaikan kebijakan luar negerinya untuk mempertahankan posisi dan pengaruhnya. Misalnya, di kawasan Asia-Pasifik, negara-negara seperti Indonesia harus menyeimbangkan hubungan antara Amerika Serikat, yang memiliki kepentingan strategis di kawasan, dengan Tiongkok yang semakin agresif dalam memperluas pengaruhnya melalui proyek-proyek seperti Inisiatif Sabuk dan Jalan (Belt and Road Initiative).\n" +
                    "\n" +
                    "Diplomasi juga berperan penting dalam memperkuat hubungan bilateral dan multilateral antar negara. Melalui pertemuan-pertemuan bilateral, negara-negara dapat membahas isu-isu yang spesifik dan memperkuat kerja sama dalam berbagai bidang, seperti perdagangan, pendidikan, dan pertukaran budaya. Sementara itu, melalui forum-forum multilateral seperti ASEAN, Uni Eropa, dan G20, negara-negara dapat bekerja sama untuk menangani isu-isu global yang memerlukan solusi kolektif, seperti penanganan pandemi, pengaturan arus perdagangan global, dan keamanan pangan.\n" +
                    "\n" +
                    "Meskipun tantangan yang dihadapi dalam hubungan internasional semakin kompleks, diplomasi tetap menjadi alat utama untuk menciptakan perdamaian dan kerja sama internasional. Artikel ini bertujuan untuk memberikan pemahaman mendalam tentang peran diplomasi dalam hubungan antar negara, proses pembentukan kebijakan luar negeri, serta tantangan-tantangan yang dihadapi dalam hubungan internasional saat ini. Dengan memahami peran dan dinamika diplomasi, diharapkan masyarakat dapat lebih menghargai pentingnya dialog dan kerja sama internasional dalam menjaga stabilitas dunia dan kesejahteraan bersama."),
            Article("Kebijakan Publik dan Implementasinya", "Kebijakan publik sangat mempengaruhi kehidupan masyarakat. Artikel ini menjelaskan proses pembuatan kebijakan publik, tantangan dalam implementasinya, dan bagaimana kebijakan yang baik dapat memberikan dampak positif bagi masyarakat.", R.drawable.article_7, "Kebijakan publik adalah serangkaian tindakan dan keputusan yang diambil oleh pemerintah untuk mengatasi berbagai masalah yang ada di masyarakat. Kebijakan ini mencakup banyak bidang, seperti kesehatan, pendidikan, ekonomi, dan lingkungan, yang semuanya memiliki peran penting dalam menentukan arah pembangunan suatu negara. Proses pembuatan kebijakan publik dimulai dari identifikasi masalah, penetapan agenda, formulasi kebijakan, hingga implementasi dan evaluasi. Dalam setiap tahap, berbagai pihak terlibat untuk memberikan masukan dan mencoba mempengaruhi kebijakan yang dihasilkan agar sesuai dengan kepentingan mereka.\n" +
                    "\n" +
                    "Proses ini dimulai dengan perumusan masalah, di mana pemerintah harus memahami dan mendefinisikan dengan jelas permasalahan yang dihadapi masyarakat. Masalah ini bisa teridentifikasi melalui data statistik, aspirasi masyarakat, atau laporan media. Setelah masalah ditetapkan, pemerintah akan menentukan prioritas mana yang akan dimasukkan ke dalam agenda kebijakan, mengingat tidak semua masalah dapat diselesaikan sekaligus. Tahap berikutnya adalah merumuskan berbagai alternatif kebijakan yang bisa diterapkan untuk menyelesaikan masalah tersebut, kemudian mengambil keputusan tentang kebijakan mana yang paling sesuai.\n" +
                    "\n" +
                    "Setelah kebijakan diputuskan, langkah selanjutnya adalah implementasi, yang sering kali melibatkan koordinasi antar lembaga pemerintah dan pemangku kepentingan lainnya. Implementasi yang baik memerlukan perencanaan matang dan alokasi sumber daya yang tepat. Kendala seperti perbedaan kondisi di lapangan atau kurangnya dukungan sumber daya sering kali menjadi hambatan dalam pelaksanaan kebijakan. Oleh karena itu, komunikasi yang baik dan fleksibilitas dalam penyesuaian kebijakan sangat penting agar kebijakan dapat diterapkan dengan efektif. Proses ini kemudian diakhiri dengan evaluasi untuk menilai apakah kebijakan telah mencapai tujuan yang diinginkan dan apa yang perlu diperbaiki ke depannya.\n" +
                    "\n" +
                    "Kendala dalam setiap tahap pembuatan kebijakan publik memang kerap muncul. Misalnya, dalam pengambilan keputusan, perbedaan kepentingan antara berbagai pihak bisa memperlambat proses dan membuat kebijakan yang dihasilkan kurang optimal. Sementara itu, dalam tahap implementasi, kurangnya koordinasi antar lembaga atau keterbatasan sumber daya sering kali membuat kebijakan tidak berjalan sebagaimana mestinya. Untuk mengatasi ini, evaluasi kebijakan menjadi kunci penting dalam menentukan keberhasilan kebijakan dan memastikan agar kebijakan yang telah diimplementasikan dapat memberikan dampak yang positif bagi masyarakat.\n" +
                    "\n" +
                    "Meskipun demikian, kebijakan publik yang dirancang dengan baik akan mampu memberikan manfaat yang signifikan bagi masyarakat. Kebijakan yang berbasis data, partisipatif, dan mempertimbangkan kondisi lokal dapat menciptakan perubahan nyata dalam kehidupan sehari-hari. Misalnya, kebijakan di bidang kesehatan yang memperhatikan akses layanan kesehatan yang merata dapat meningkatkan kualitas hidup masyarakat. Begitu pula, kebijakan di bidang pendidikan yang fokus pada peningkatan kualitas pengajaran dapat menghasilkan generasi yang lebih siap menghadapi tantangan masa depan. Oleh karena itu, perumusan dan pelaksanaan kebijakan publik yang baik memerlukan kerjasama yang erat antara pemerintah dan masyarakat, agar tercipta kebijakan yang responsif dan bermanfaat."),
            Article("Politik Lingkungan", "Dalam menghadapi isu perubahan iklim, politik lingkungan menjadi semakin relevan. Artikel ini membahas bagaimana kebijakan lingkungan dibentuk, tantangan yang dihadapi, dan peran masyarakat dalam mendorong kebijakan yang berkelanjutan untuk melindungi lingkungan.", R.drawable.article_8, "Dalam menghadapi isu perubahan iklim yang semakin mendesak, politik lingkungan telah menjadi semakin relevan dan penting dalam pembuatan kebijakan publik. Kebijakan lingkungan bertujuan untuk mengatasi berbagai tantangan yang dihadapi, seperti penurunan kualitas udara, pencemaran, deforestasi, dan kehilangan keanekaragaman hayati. Proses pembentukan kebijakan lingkungan dimulai dengan identifikasi masalah lingkungan yang perlu diatasi, diikuti dengan pengumpulan data dan informasi yang akurat untuk merumuskan kebijakan yang tepat. Pemerintah bersama dengan berbagai pemangku kepentingan, termasuk organisasi non-pemerintah, sektor swasta, dan masyarakat sipil, bekerja sama untuk merumuskan kebijakan yang efektif.\n" +
                    "\n" +
                    "Namun, dalam proses ini, berbagai tantangan sering kali muncul. Salah satu tantangan utama adalah adanya perbedaan kepentingan antara sektor ekonomi dan lingkungan. Seringkali, keputusan yang diambil untuk mendukung pertumbuhan ekonomi dapat berdampak negatif pada lingkungan. Oleh karena itu, diperlukan pendekatan yang seimbang antara pembangunan ekonomi dan perlindungan lingkungan agar kebijakan yang dihasilkan tidak hanya memberikan manfaat jangka pendek, tetapi juga berkelanjutan dalam jangka panjang. Selain itu, keterbatasan sumber daya, baik finansial maupun teknis, juga dapat menjadi hambatan dalam implementasi kebijakan lingkungan yang efektif.\n" +
                    "\n" +
                    "Peran masyarakat dalam mendorong kebijakan lingkungan yang berkelanjutan sangatlah penting. Kesadaran masyarakat tentang isu-isu lingkungan dapat mendorong pemerintah untuk mengambil tindakan yang lebih proaktif. Melalui partisipasi aktif, seperti kampanye, pendidikan lingkungan, dan advokasi, masyarakat dapat memberikan tekanan kepada pemerintah untuk mengimplementasikan kebijakan yang lebih baik. Selain itu, masyarakat juga dapat berkontribusi dengan mengadopsi praktik ramah lingkungan dalam kehidupan sehari-hari, seperti pengurangan penggunaan plastik, daur ulang, dan konservasi energi. \n" +
                    "\n" +
                    "Oleh karena itu, kolaborasi antara pemerintah dan masyarakat sangat diperlukan untuk menciptakan kebijakan lingkungan yang efektif dan berkelanjutan. Kebijakan yang dirancang dengan melibatkan masukan dari berbagai pihak akan lebih responsif terhadap kebutuhan masyarakat dan dapat memberikan dampak positif bagi lingkungan. Dengan pendekatan yang komprehensif dan kerjasama yang baik, diharapkan kebijakan lingkungan dapat membantu melindungi ekosistem dan menjaga keberlanjutan sumber daya alam bagi generasi mendatang."),
            Article("Media dan Politik", "Media memiliki pengaruh besar dalam membentuk opini publik dan berperan sebagai pengawas pemerintahan. Artikel ini mengeksplorasi hubungan antara media dan politik, serta tantangan yang dihadapi media dalam menyampaikan informasi yang akurat di tengah informasi yang beredar.", R.drawable.article_9, "Media memegang peranan penting dalam membentuk opini publik dan bertindak sebagai pengawas terhadap pemerintah. Melalui pemberitaan yang objektif dan analitis, media dapat memengaruhi persepsi masyarakat terhadap isu-isu politik, kebijakan publik, dan tindakan pemerintah. Hubungan antara media dan politik sangat kompleks, di mana keduanya saling mempengaruhi satu sama lain. Di satu sisi, media berfungsi untuk menginformasikan masyarakat, memberikan platform bagi diskusi, dan mendorong partisipasi publik. Di sisi lain, pemerintah juga berusaha memanfaatkan media untuk menyampaikan pesan-pesan politiknya dan membangun citra yang positif.\n" +
                    "\n" +
                    "Namun, di era informasi yang semakin cepat ini, media menghadapi berbagai tantangan dalam menyampaikan informasi yang akurat dan berimbang. Salah satu tantangan terbesar adalah maraknya disinformasi dan hoaks yang dapat menyesatkan publik. Di tengah arus informasi yang deras, sulit bagi masyarakat untuk memilah mana berita yang kredibel dan mana yang tidak. Hal ini menuntut media untuk lebih teliti dalam menyajikan berita, serta berkomitmen untuk melakukan fact-checking agar informasi yang disampaikan dapat dipercaya.\n" +
                    "\n" +
                    "Selain itu, kebebasan pers juga menjadi isu penting dalam hubungan antara media dan politik. Di beberapa negara, termasuk Indonesia, masih ada tekanan dari pemerintah dan kelompok tertentu yang berusaha membatasi kebebasan media dalam melaporkan berita. Dalam kondisi seperti ini, jurnalis sering kali menghadapi risiko ketika mencoba untuk melaporkan fakta yang tidak sesuai dengan kepentingan politik. Oleh karena itu, perlindungan terhadap kebebasan pers sangat penting agar media dapat menjalankan fungsinya sebagai watchdog yang efektif.\n" +
                    "\n" +
                    "Media juga perlu mengedukasi masyarakat tentang cara mengakses informasi dengan bijak. Upaya ini dapat dilakukan melalui kampanye literasi media yang membantu publik memahami cara menilai sumber informasi dan membedakan berita yang valid dari yang tidak. Dengan demikian, masyarakat dapat lebih kritis dalam menerima informasi dan terlibat dalam diskusi yang lebih sehat mengenai isu-isu politik.\n" +
                    "\n" +
                    "Dalam menghadapi tantangan-tantangan ini, kolaborasi antara media, pemerintah, dan masyarakat sangat diperlukan untuk menciptakan ekosistem informasi yang sehat. Media yang bebas dan bertanggung jawab akan berkontribusi pada pembangunan demokrasi yang lebih baik, di mana publik memiliki akses terhadap informasi yang akurat dan dapat membuat keputusan yang tepat dalam konteks politik dan sosial. Dengan memperkuat peran media sebagai pengawas dan pemberi informasi, diharapkan masyarakat dapat lebih terlibat dalam proses demokrasi dan mempertahankan hak-hak mereka sebagai warga negara."),
            Article("Tantangan Politik di Era Digital", "Era digital membawa tantangan baru bagi politik, termasuk penyebaran informasi palsu dan kampanye online. Artikel ini membahas dampak media sosial terhadap politik, bagaimana politikus beradaptasi dengan teknologi baru, dan pentingnya literasi digital bagi masyarakat.", R.drawable.article_10, "Era digital telah membawa tantangan baru yang signifikan bagi dunia politik, terutama dengan munculnya media sosial sebagai platform utama untuk komunikasi dan informasi. Penyebaran informasi palsu dan kampanye online menjadi isu krusial yang perlu dihadapi oleh politisi, pemerintah, dan masyarakat. Media sosial memungkinkan informasi menyebar dengan cepat dan luas, tetapi juga menjadi sarana bagi penyebaran hoaks dan propaganda yang dapat memengaruhi opini publik dan proses pemilu. Dalam konteks ini, pemahaman yang baik tentang cara kerja media sosial dan dampaknya terhadap politik menjadi sangat penting.\n" +
                    "\n" +
                    "Politikus kini harus beradaptasi dengan teknologi baru untuk tetap relevan dan berinteraksi dengan konstituen mereka. Banyak politisi yang menggunakan media sosial untuk menjangkau pemilih, menyampaikan pesan politik, dan membangun citra publik. Platform seperti Twitter, Facebook, dan Instagram memungkinkan mereka untuk berkomunikasi secara langsung dan lebih personal dengan masyarakat. Namun, penggunaan media sosial juga membawa risiko, karena setiap pernyataan atau tindakan dapat dengan mudah dibagikan, diubah, dan disalahartikan. Politisi harus bijaksana dalam menggunakan platform ini agar tidak terjebak dalam kontroversi yang dapat merugikan reputasi mereka.\n" +
                    "\n" +
                    "Pentingnya literasi digital bagi masyarakat juga tidak bisa diabaikan. Dalam menghadapi arus informasi yang deras, masyarakat perlu memiliki keterampilan untuk menilai kebenaran dan keandalan informasi yang mereka terima. Literasi digital mencakup kemampuan untuk mengenali sumber informasi yang kredibel, memahami konteks berita, dan mengevaluasi argumen yang disajikan. Dengan literasi digital yang baik, masyarakat dapat menjadi konsumen informasi yang lebih kritis dan mampu membedakan antara fakta dan opini, serta informasi yang benar dan yang salah.\n" +
                    "\n" +
                    "Dalam menghadapi tantangan ini, kolaborasi antara pemerintah, lembaga pendidikan, dan organisasi masyarakat sipil sangat diperlukan untuk meningkatkan literasi digital. Program-program pendidikan yang mengajarkan keterampilan berpikir kritis dan cara menggunakan media sosial secara bertanggung jawab dapat membantu masyarakat untuk lebih memahami dampak media digital dalam politik. Dengan demikian, diharapkan masyarakat dapat berpartisipasi secara aktif dan cerdas dalam proses demokrasi, serta mampu menghadapi tantangan yang ditimbulkan oleh era digital. \n" +
                    "\n" +
                    "Dengan memahami dinamika yang terjadi di era digital, semua pihak diharapkan dapat berkontribusi pada terciptanya lingkungan politik yang lebih sehat dan transparan. Media sosial dapat menjadi alat yang kuat untuk pemberdayaan masyarakat, asalkan digunakan dengan bijak dan bertanggung jawab.")
        )

        recyclerView.adapter = ArticleAdapter(articleList) { article ->
            val intent = Intent(this, DetailActivity::class.java).apply {
                putExtra("TITLE", article.title)
                putExtra("OVERVIEW", article.fullOverview)
                putExtra("IMAGE_RESOURCE", article.imageResId)
            }
            startActivity(intent)
        }
    }
    override fun onCreateOptionsMenu(menu: Menu?): Boolean {
        menuInflater.inflate(R.menu.menu_main, menu)
        return true
    }
    override fun onOptionsItemSelected(item: MenuItem): Boolean {
        return when (item.itemId) {
            R.id.about_page -> {
                val intent = Intent(this, AboutActivity::class.java)
                startActivity(intent)
                true
            }
            else -> super.onOptionsItemSelected(item)
        }
    }
}